vim.keymap.set("n", "<leader>x", function()
  vim.cmd("update")
  vim.cmd("vert split")
	local file = vim.fn.shellescape(vim.fn.expand("%"))
  vim.cmd("terminal gcc -g -O0 -Wall -Wextra -Wconversion -Wsign-conversion -Wshadow " .. file .. " && ./a.out")
	vim.cmd("startinsert")
end, { buffer = true, desc = "Compile and run current c file" })
