vim.keymap.set("n", "<leader>x", function()
  vim.cmd("update")
  vim.cmd("vert split")
  vim.cmd("terminal uv run python " .. vim.fn.shellescape(vim.fn.expand("%")))
	vim.cmd("startinsert")
end, { buffer = true, desc = "Run current Python file with uv" })
